### ISSUE TITLE
Высота картинки на бекграунде

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#12]
высота 600 пикселей 

Если картинка из макета не подходит, я сделаю такую, которая подойдет. только дайте параметры 
![image](https://cloud.githubusercontent.com/assets/11739563/8916838/d798081a-34b6-11e5-8c4f-ef58635264ef.png)

**Comment by Wilvarin** [comment]
подходит. там из-за фиксированой менюшки немного съехало, поправим.

**Comment by Wilvarin** [comment]
Оля подберет текстуру и я поставлю, для маленьких экранов.

**Comment by olleskiv** [comment]
Заказчик скинул еще картинок, так что я туда вообще другую поставлю. Текступу тоже сделаем

**Comment by Wilvarin** [comment]
+
