### ISSUE TITLE
сделать полосочки в меню, как в шаблоне 

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#14]
![image](https://cloud.githubusercontent.com/assets/11739563/8916937/87e5c5d6-34b7-11e5-821a-8a61b005dece.png)
![image](https://cloud.githubusercontent.com/assets/11739563/8916943/8eab7e9c-34b7-11e5-8d9f-8448b2d710f2.png)

**Comment by Wilvarin** [comment]
+

**Comment by Wilvarin** [comment]
и отступ сделал как в шаблоне
