### ISSUE TITLE
Меню 2

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#23]
Сделайте все же такое меню, как я нарисовала

Которое сейчас крутое, но оно немного из стиля выбивается

![image](https://cloud.githubusercontent.com/assets/11739563/8917870/6df6e708-34bd-11e5-80e3-3a80bd7aee48.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8943715/c532b282-3584-11e5-8876-3ec3e6fd038e.png)
вот так хорошо?

**Comment by Wilvarin** [comment]
ай ай ай текст забыл влево сместить. ай ай ай

**Comment by olleskiv** [comment]
Надо на сайте посмотреть. Я бы лучше просто подчеркиванием сделала

**Comment by Wilvarin** [comment]
примеряем все варианты)

**Comment by Wilvarin** [comment]
Оля одобрила.
