### ISSUE TITLE
убрать отступ от полосочки

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#27]
![image](https://cloud.githubusercontent.com/assets/11739563/9154424/1adc8e96-3e96-11e5-8002-729d34aa4ad9.png)

**Comment by Wilvarin** [comment]
стоп стоп стоп. 
ты сказала сделать как в шаблоне, а там отступ есть

**Comment by Wilvarin** [comment]
я не помню правда название того сайта где ты говорила смотреть.

**Comment by olleskiv** [comment]
просто убери и все

**Comment by Wilvarin** [comment]
ок.
