### ISSUE TITLE
Правильное расположение меню

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#4]
включить направляющие и посмотреть расположение текста, меню и шапки относительно друг другу

(в макете я немного не дотянула справа текст, на странице должны быть ровные отступы с обеих сторон)

![image](https://cloud.githubusercontent.com/assets/11739563/8904047/fc8dcf12-3464-11e5-8860-b9eff507f9f2.png)

**Comment by Wilvarin** [comment]
поправил
