### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#7]
Расстояния от последнего рядка текста до футера во всем документе мин 120 пикселей

Выровнять "создано TQG" с номерами. 

Сделать шрифт "подписаться на обновления" и "подписаться меньше, чтобы слова влазили целиком. Или расширить строку

![image](https://cloud.githubusercontent.com/assets/11739563/8904227/4f3b5e2c-3466-11e5-85c3-7355362552e9.png)

**Comment by Wilvarin** [comment]
готово

**Comment by olleskiv** [comment]
Расстояние от последнего рядка до футера 120 пикселей сделать на всех страницах

**Comment by Wilvarin** [comment]
готово
