### ISSUE TITLE
Меню

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#8]
Сделать тени полосочки, как на сайте-шаблоне. Сделать меню фиксированным.

![image](https://cloud.githubusercontent.com/assets/11739563/8904352/50f90826-3467-11e5-9f27-f602ee0e38db.png)

![image](https://cloud.githubusercontent.com/assets/11739563/8904382/8f480136-3467-11e5-9902-9ca1abb0a740.png)

**Comment by Wilvarin** [comment]
полосочка +
