### ISSUE TITLE
Слово "поиск" не по центру

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/metal#9]
![image](https://cloud.githubusercontent.com/assets/11739563/8904396/ac8357b4-3467-11e5-96d1-c4cc34dfc4e7.png)

**Comment by Wilvarin** [comment]
готово

**Comment by olleskiv** [comment]
Еще вертикально
![image](https://cloud.githubusercontent.com/assets/11739563/8917285/cf352664-34b9-11e5-8fb5-2c15f8a357f9.png)

**Comment by Wilvarin** [comment]
=))

**Comment by Wilvarin** [comment]
+
